-- init_goalscorers.sql
-- Insert goal scorers for Golden Boot predictions
-- Run this in Supabase SQL Editor after init_teams.sql
--
-- Top 100 Golden Boot candidates ordered by bookmaker odds (lowest = favourite).
-- This script INSERTs new players; existing ones are skipped via ON CONFLICT.
-- To fully replace the list, manually run `DELETE FROM goal_scorers;` first.


INSERT INTO goal_scorers (player_name, team) VALUES
('Kylian Mbappe', 'France'),
('Harry Kane', 'England'),
('Erling Haaland', 'Norway'),
('Mikel Oyarzabal', 'Spain'),
('Lionel Messi', 'Argentina'),
('Cristiano Ronaldo', 'Portugal'),
('Lamine Yamal', 'Spain'),
('Ousmane Dembele', 'France'),
('Raphinha', 'Brazil'),
('Julian Alvarez', 'Argentina'),
('Vinicius Junior', 'Brazil'),
('Kai Havertz', 'Germany'),
('Lautaro Martinez', 'Argentina'),
('Cody Gakpo', 'Netherlands'),
('Romelu Lukaku', 'Belgium'),
('Mikel Merino', 'Spain'),
('Donyell Malen', 'Netherlands'),
('Jean-Philippe Mateta', 'France'),
('Ferran Torres', 'Spain'),
('Bukayo Saka', 'England'),
('Igor Thiago', 'Belgium'),
('Michael Olise', 'France'),
('Endrick', 'Brazil'),
('Deniz Undav', 'Germany'),
('Memphis Depay', 'Netherlands'),
('Luis Diaz', 'Colombia'),
('Desire Doue', 'France'),
('Matheus Cunha', 'Brazil'),
('Luis Javier Suarez', 'Colombia'),
('Morgan Rogers', 'England'),
('Santiago Gimenez', 'Mexico'),
('Darwin Nunez', 'Uruguay'),
('Eberechi Eze', 'England'),
('Jude Bellingham', 'England'),
('Alexander Isak', 'Sweden'),
('Goncalo Ramos', 'Portugal'),
('Jamal Musiala', 'Germany'),
('Leandro Trossard', 'Belgium'),
('Marcus Rashford', 'England'),
('Ollie Watkins', 'England'),
('Florian Wirtz', 'Germany'),
('Neymar', 'Brazil'),
('Enner Valencia', 'Ecuador'),
('Bruno Fernandes', 'Portugal'),
('Nick Woltemade', 'Germany'),
('Alexander Sorloth', 'Norway'),
('Dani Olmo', 'Spain'),
('Folarin Balogun', 'USA'),
('Kevin De Bruyne', 'Belgium'),
('Christian Pulisic', 'USA'),
('Anthony Gordon', 'England'),
('Rafael Leao', 'Portugal'),
('Jeremy Doku', 'Belgium'),
('Sadio Mane', 'Senegal'),
('Marcus Thuram', 'France'),
('Brian Brobbey', 'Netherlands'),
('Leroy Sane', 'Germany'),
('Viktor Gyokeres', 'Sweden'),
('Raul Jimenez', 'Mexico'),
('Mohamed Salah', 'Egypt'),
('Joao Felix', 'Portugal'),
('Ayase Ueda', 'Japan'),
('Omar Marmoush', 'Egypt'),
('Mohammed Kudus', 'Ghana'),
('Charles De Ketelaere', 'Belgium'),
('Nicolas Jackson', 'Senegal'),
('Rayan Cherki', 'France'),
('Jonathan David', 'Canada'),
('Breel Embolo', 'Switzerland'),
('Christoph Baumgartner', 'Austria'),
('Ayoub El Kaabi', 'Morocco'),
('Rayan', 'Brazil'),
('Pedro Neto', 'Portugal'),
('Haji Wright', 'USA'),
('Nico Williams', 'Spain'),
('Ante Budimir', 'Croatia'),
('Ricardo Pepi', 'USA'),
('Son Heung-min', 'South Korea'),
('Federico Valverde', 'Uruguay'),
('Bradley Barcola', 'France'),
('Gabriel Martinelli', 'Brazil'),
('Ismaila Sarr', 'Senegal'),
('Arda Guler', 'Turkey'),
('Noa Lang', 'Netherlands'),
('Edin Dzeko', 'Bosnia & Herzegovina'),
('Ivan Toney', 'England'),
('Kang-In Lee', 'South Korea'),
('Kerem Akturkoglu', 'Turkey'),
('Ange-Yoan Bonny', 'Ivory Coast'),
('Enzo Fernandez', 'Argentina'),
('Promise David', 'Canada'),
('Kenan Yildiz', 'Turkey'),
('Patrik Schick', 'Czech Republic'),
('Jorgen Strand Larsen', 'Norway'),
('Riyad Mahrez', 'Algeria'),
('Armando Gonzalez', 'Mexico'),
('Julian Quinones', 'Mexico'),
('Sepe Elye Wahi', 'Ivory Coast'),
('James Rodriguez', 'Colombia'),
('Scott McTominay', 'Scotland')
ON CONFLICT (player_name) DO NOTHING;
