-- init_teams.sql
-- Auto-generated from matches.json - ACTUAL 2026 World Cup teams
-- All 48 teams for 2026 World Cup

DELETE FROM teams;

INSERT INTO teams (team_name, group_name) VALUES
('Czech Republic', 'A'),
('Mexico', 'A'),
('South Africa', 'A'),
('South Korea', 'A'),
('Bosnia & Herzegovina', 'B'),
('Canada', 'B'),
('Qatar', 'B'),
('Switzerland', 'B'),
('Brazil', 'C'),
('Haiti', 'C'),
('Morocco', 'C'),
('Scotland', 'C'),
('Australia', 'D'),
('Paraguay', 'D'),
('Turkey', 'D'),
('USA', 'D'),
('Curaçao', 'E'),
('Ecuador', 'E'),
('Germany', 'E'),
('Ivory Coast', 'E'),
('Japan', 'F'),
('Netherlands', 'F'),
('Sweden', 'F'),
('Tunisia', 'F'),
('Belgium', 'G'),
('Egypt', 'G'),
('Iran', 'G'),
('New Zealand', 'G'),
('Cape Verde', 'H'),
('Saudi Arabia', 'H'),
('Spain', 'H'),
('Uruguay', 'H'),
('France', 'I'),
('Iraq', 'I'),
('Norway', 'I'),
('Senegal', 'I'),
('Algeria', 'J'),
('Argentina', 'J'),
('Austria', 'J'),
('Jordan', 'J'),
('Colombia', 'K'),
('DR Congo', 'K'),
('Portugal', 'K'),
('Uzbekistan', 'K'),
('Croatia', 'L'),
('England', 'L'),
('Ghana', 'L'),
('Panama', 'L');
